version: "3.8"
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile_bn
    volumes:
      - "./resources:/app"
    entrypoint:
      - java
      - -jar
      - /app/review.jar
    restart: always
    ports:
      - "8080:8080"
    expose:
      - "8080"
  client:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile_fn
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
